# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LE1lDsLXptSapBjP8mghy71gZrDQ5oeo
"""

pip install streamlit

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import matplotlib.pyplot as plt

# 1. LOAD AND SPLIT THE MNIST DATASET
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

# 2. PREPROCESS THE DATA
# Scale pixel values from 0-255 to 0-1
X_train = X_train / 255.0
X_test = X_test / 255.0

# 3. BUILD THE NEURAL NETWORK ARCHITECTURE
model = models.Sequential([
    # Flatten the 28x28 image matrices into a 1D array of 784 pixels
    layers.Flatten(input_shape=(28, 28)),

    # Hidden layer with 128 neurons to detect shapes/edges
    layers.Dense(128, activation='relu'),

    # Output layer with 10 neurons (one for each digit 0-9)
    layers.Dense(10, activation='softmax')
])

# 4. COMPILE THE MODEL
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 5. TRAIN THE MODEL
print("--- Training Started ---")
model.fit(X_train, y_train, epochs=5, batch_size=32)

# 6. EVALUATE THE MODEL ON UNSEEN TEST DATA
print("\n--- Evaluation on Test Data ---")
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc * 100:.2f}%")

# 7. MAKE A PREDICTION
# Grab the very first image from the test set
sample_image = X_test[0]
true_label = y_test[0]

# Reshape the image because the model expects a batch of images
prediction = model.predict(np.expand_dims(sample_image, axis=0))
predicted_digit = np.argmax(prediction)

# Display the result
print(f"\nPredicted Digit: {predicted_digit} (True Label: {true_label})")

# Save the trained model
model.save('digit_model.h5')

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image, ImageOps

# 1. Configure the Web Page Layout
st.set_page_config(page_title="Digit Recogniser", layout="centered")
st.title("🔢 Handwritten Digit Recogniser")
st.write("Upload a clear photo of a single handwritten digit (0-9) to see the AI predict it!")

# 2. Load the Saved Model safely using caching
@st.cache_resource
def load_saved_model():
    return tf.keras.models.load_model('digit_model.h5')

try:
    model = load_saved_model()
except Exception as e:
    st.error("Could not find 'digit_model.h5'. Make sure it is uploaded to your GitHub repository.")

# 3. Create the Image Upload Interface
uploaded_file = st.file_uploader("Choose an image file...", type=["png", "jpg", "jpeg"])

if uploaded_file is not None:
    # Display the uploaded image to the user
    image = Image.open(uploaded_file)
    st.image(image, caption="Your Uploaded Image", width=200)

    # 4. Process the image to match the training data
    with st.spinner("Processing image and predicting..."):
        # Convert to grayscale
        img_gray = image.convert('L')

        # Invert colors (MNIST needs white text on a black background)
        img_inverted = ImageOps.invert(img_gray)

        # Resize to exactly 28x28 pixels
        img_resized = img_inverted.resize((28, 28))

        # Format into a normalized NumPy array (0.0 to 1.0)
        img_array = np.array(img_resized) / 255.0

        # Reshape to (1, 28, 28) to match the model's batch expectation
        img_array = np.expand_dims(img_array, axis=0)

        # 5. Make the Prediction
        prediction = model.predict(img_array)
        predicted_digit = np.argmax(prediction)
        confidence = np.max(prediction) * 100

        # 6. Display Results beautifully
        st.success(f"### 🔮 Prediction: This is a **{predicted_digit}**")
        st.metric(label="Model Confidence", value=f"{confidence:.2f}%")
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np

# 1. LOAD AND SPLIT THE MNIST DATASET
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

# 2. PREPROCESS THE DATA
# Scale pixel values from 0-255 to 0-1
X_train = X_train / 255.0
X_test = X_test / 255.0

# 3. BUILD THE NEURAL NETWORK ARCHITECTURE
model = models.Sequential([
    # Flatten the 28x28 image matrices into a 1D array of 784 pixels
    layers.Flatten(input_shape=(28, 28)),

    # Hidden layer with 128 neurons to detect shapes/edges
    layers.Dense(128, activation='relu'),

    # Output layer with 10 neurons (one for each digit 0-9)
    layers.Dense(10, activation='softmax')
])

# 4. COMPILE THE MODEL
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 5. TRAIN THE MODEL
print("--- Training Started ---")
model.fit(X_train, y_train, epochs=5, batch_size=32)

# 6. EVALUATE THE MODEL ON UNSEEN TEST DATA
print("\n--- Evaluation on Test Data ---")
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc * 100:.2f}%")

# 7. MAKE A PREDICTION
# Grab the very first image from the test set
sample_image = X_test[0]
true_label = y_test[0]

# Reshape the image because the model expects a batch of images
prediction = model.predict(np.expand_dims(sample_image, axis=0))
predicted_digit = np.argmax(prediction)

# Display the result
print(f"\nPredicted Digit: {predicted_digit} (True Label: {true_label})")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# from PIL import Image, ImageOps
# 
# # 1. Configure the Web Page Layout
# st.set_page_config(page_title="Digit Recogniser", layout="centered")
# st.title("🔢 Handwritten Digit Recogniser")
# st.write("Upload a clear photo of a single handwritten digit (0-9) to see the AI predict it!")
# 
# # 2. Load the Saved Model safely using caching
# @st.cache_resource
# def load_saved_model():
#     return tf.keras.models.load_model('digit_model.h5')
# 
# try:
#     model = load_saved_model()
# except Exception as e:
#     st.error("Could not find 'digit_model.h5'. Make sure it is uploaded to your GitHub repository.")
# 
# # 3. Create the Image Upload Interface
# uploaded_file = st.file_uploader("Choose an image file...", type=["png", "jpg", "jpeg"])
# 
# if uploaded_file is not None:
#     # Display the uploaded image to the user
#     image = Image.open(uploaded_file)
#     st.image(image, caption="Your Uploaded Image", width=200)
# 
#     # 4. Process the image to match the training data
#     with st.spinner("Processing image and predicting..."):
#         # Convert to grayscale
#         img_gray = image.convert('L')
# 
#         # Invert colors (MNIST needs white text on a black background)
#         img_inverted = ImageOps.invert(img_gray)
# 
#         # Resize to exactly 28x28 pixels
#         img_resized = img_inverted.resize((28, 28))
# 
#         # Format into a normalized NumPy array (0.0 to 1.0)
#         img_array = np.array(img_resized) / 255.0
# 
#         # Reshape to (1, 28, 28) to match the model's batch expectation
#         img_array = np.expand_dims(img_array, axis=0)
# 
#         # 5. Make the Prediction
#         prediction = model.predict(img_array)
#         predicted_digit = np.argmax(prediction)
#         confidence = np.max(prediction) * 100
# 
#         # 6. Display Results beautifully
#         st.success(f"### 🔮 Prediction: This is a **{predicted_digit}**")
#         st.metric(label="Model Confidence", value=f"{confidence:.2f}%")

!streamlit run app.py